server:
  port: 9090

spring:
  instance:
    hostname: localhost
  config:
    activate:
      on-profile: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
