spring:
  config:
    activate:
      on-profile: default
  #zipkin:
  #  baseUrl: http://localhost:9411
management:
  endpoint:
    chaosmonkey:
      enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: true
      controller: true
      repository: true
      rest-controller: true
      service: true
    assaults:
      level: 1
      deterministic: false
      exceptionsActive: true
      exception:
        type: java.lang.CertificateException
        #method: findAll
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
