vets:
  cache:
    ttl: 60
    heap-size: 100

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: default
  #zipkin:
  #  baseUrl: http://localhost:9411
management:
  endpoint:
    chaosmonkey:
      enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: true
      controller: true
      repository: true
      rest-controller: true
      service: true
    assaults:
      memoryActive: true
      memoryMillisecondsHoldFilledMemory: 90000
      memoryMillisecondsWaitNextIncrease: 1000
      memoryFillIncrementFraction: 0.1
      memoryFillTargetFraction: 0.95
      runtime:
        scope:
          assault:
            cron:
              expression: */1 * * * *
server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
