spring:
  config:
    activate:
      on-profile: default
  #zipkin:
  #  baseUrl: http://localhost:9411
management:
  endpoint:
    chaosmonkey:
      enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false
    assaults:
      latencyActive: true
      latencyRangeStart: 10000
      latencyRangeEnd: 15000
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: chaos-monkey      
management:
  endpoint:
    chaosmonkey:
      enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
